apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: sa-thinking-code
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  EUREKA_INSTANCE_HOSTNAME: "api-gateway"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
