apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: sa-thinking-code
data:
  01-create-databases.sql: |
    CREATE DATABASE auth_db;
    CREATE DATABASE product_db;
    CREATE DATABASE order_shard_0;
    CREATE DATABASE order_shard_1;
    CREATE DATABASE order_shard_2;
    CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD 'replpass123';
  02-create-tables.sql: |
    \c order_shard_0
    CREATE TABLE orders (
        id BIGSERIAL PRIMARY KEY,
        customer_id BIGINT NOT NULL,
        product_id BIGINT NOT NULL,
        quantity INTEGER NOT NULL,
        total_price NUMERIC NOT NULL,
        status VARCHAR(20) NOT NULL,
        created_at TIMESTAMP NOT NULL
    );
    \c order_shard_1
    CREATE TABLE orders (
        id BIGSERIAL PRIMARY KEY,
        customer_id BIGINT NOT NULL,
        product_id BIGINT NOT NULL,
        quantity INTEGER NOT NULL,
        total_price NUMERIC NOT NULL,
        status VARCHAR(20) NOT NULL,
        created_at TIMESTAMP NOT NULL
    );
    \c order_shard_2
    CREATE TABLE orders (
        id BIGSERIAL PRIMARY KEY,
        customer_id BIGINT NOT NULL,
        product_id BIGINT NOT NULL,
        quantity INTEGER NOT NULL,
        total_price NUMERIC NOT NULL,
        status VARCHAR(20) NOT NULL,
        created_at TIMESTAMP NOT NULL
    );
