apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-hba-config
  namespace: sa-thinking-code
data:
  pg_hba.conf: |
    host    replication     replicator      0.0.0.0/0               scram-sha-256
    local   all             all                                     trust
    host    all             all             0.0.0.0/0               trust
