apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: sa-thinking-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: harirajana/sa-product-service:jenkins-build
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
